# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='labels',
        ),
    ]
