# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20160223_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='background_color',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='label',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='label',
            name='text_color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
