# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20160223_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(max_length=1000),
        ),
    ]
